name: Build Linux x86-64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    #build and install XP-CMake
    - name: Checkout XP-CMake repo
      uses: actions/checkout@v4
      with:
        repository: aczwink/XP-CMake
        path: xpcmake

    - name: Create build directory for XP-CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/xpcmake/_build -S ${{github.workspace}}/xpcmake

    - name: Build XP-CMake
      run: cmake --build ${{github.workspace}}/xpcmake/_build --config ${{env.BUILD_TYPE}}

    - name: Install XP-CMake
      run: sudo make install
      working-directory: ${{github.workspace}}/xpcmake/_build


    #build and install Std++
    - name: Checkout Std++ repo
      uses: actions/checkout@v4
      with:
        repository: aczwink/StdPlusPlus
        path: stdpp

    - name: Create build directory for Std++
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/stdpp/_build -S ${{github.workspace}}/stdpp

    - name: Build Std++
      run: cmake --build ${{github.workspace}}/stdpp/_build --config ${{env.BUILD_TYPE}}

    - name: Install Std++
      run: sudo make install
      working-directory: ${{github.workspace}}/stdpp/_build



    #build EDMW-Modding-Tools
    - name: Checkout EDMW-Modding-Tools repo
      uses: actions/checkout@v4
      with:
        path: edmw

    - name: Configure build directory for EDMW-Modding-Tools
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/edmw/_build -S ${{github.workspace}}/edmw

    - name: Build EDMW-Modding-Tools
      run: cmake --build ${{github.workspace}}/edmw/_build --config ${{env.BUILD_TYPE}}
